services:
  redis:
    image: redis:7.2.3-alpine
    container_name: test-das-redis
    restart: always
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    network_mode: host
    # networks:
    #   - app_network

  mongodb:
    image: mongo:latest
    container_name: test-das-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    healthcheck:
      test:
        [
          "CMD",
          "echo",
          'db.runCommand("ping").ok',
          "|",
          "mongo",
          "das-mongo:27017/test",
          "--quiet",
        ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    network_mode: host
    
    # networks:
    #   - app_network


  metta-parser:
    image: trueagi/das:0.5.4-metta-parser
    container_name: test-das-metta-parser
    working_dir: /opt/das-metta-parser
    command: db_loader /tmp/animals.metta
    volumes:
      - ./data:/tmp
    environment:
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: localhost
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: localhost
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root
      DAS_DATABASE_USERNAME: root
      DAS_DATABASE_PASSWORD: root
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: on-failure
    network_mode: host

    # networks:
    #   - app_network


  das-attention-broker:
    # How to build:
    # Clone the das-node repository
    # Run:
    # ./scripts/docker_image_build.sh
    # build: ./docker_das_node
    working_dir: /opt
    image: das-attention-broker-builder
    container_name: test-das-attention-broker
    command: ./bin/attention_broker_service 37007
    # command: sleep infinity
    ports:
      - 37007:37007
    volumes:
      - ../../../src:/opt
    depends_on:
      - mongodb
      - redis
      - metta-parser
    restart: on-failure
    environment:
      DAS_MONGODB_NAME: das
      DAS_MONGODB_HOSTNAME: localhost
      DAS_MONGODB_PORT: 27017
      DAS_REDIS_HOSTNAME: localhost
      DAS_REDIS_PORT: 6379
      DAS_MONGODB_USERNAME: root
      DAS_MONGODB_PASSWORD: root
    network_mode: host
    
    # networks:
    #   - app_network


  # das-query-agent:
  #   # How to build:
  #   # Clone the das-node repository
  #   # Run:
  #   # ./scripts/docker_image_build.sh
  #   # build: ./docker_das_node
  #   working_dir: /opt
  #   image: das-attention-broker-builder
  #   container_name: test-das-query-agent-node
  #   command: ./bin/query_broker 35700
  #   # command: sleep infinity
  #   ports:
  #     - 35700:35700
  #     # - 6379:6379
  #   volumes:
  #     - ../../../src:/opt
  #   restart: on-failure
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - metta-parser
  #     - das-attention-broker
  #   environment:
  #     DAS_MONGODB_NAME: das
  #     DAS_MONGODB_HOSTNAME: localhost
  #     DAS_MONGODB_PORT: 27017
  #     DAS_REDIS_HOSTNAME: 0.0.0.0
  #     DAS_REDIS_PORT: 6379
  #     DAS_MONGODB_USERNAME: root
  #     DAS_MONGODB_PASSWORD: root
  #   network_mode: host
    
    # networks:
    #   - app_network


  # das-link-create-agent:
  #   # How to build:
  #   # Clone the das-node repository
  #   # Run:
  #   # ./scripts/docker_image_build.sh
  #   # build: ./docker_das_node
  #   image: das-attention-broker-builder
  #   container_name: test-das-link-create-agent-node
  #   working_dir: /opt
  #   command: ./bin/link_creation_server --type server --config_file /tmp/config
  #   # command: sleep infinity
  #   volumes:
  #     - ./data:/tmp
  #     - ../../../src:/opt
  #   ports:
  #     # - 35700:35700
  #     - 9090:9090
  #   restart: on-failure
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - metta-parser
  #     - das-attention-broker
  #     - das-query-agent
  #   # environment:
  #   #   DAS_MONGODB_NAME: das
  #   #   DAS_MONGODB_HOSTNAME: localhost
  #   #   DAS_MONGODB_PORT: 27017
  #   #   DAS_REDIS_HOSTNAME: 0.0.0.0
  #   #   DAS_REDIS_PORT: 6378
  #   #   DAS_MONGODB_USERNAME: root
  #   #   DAS_MONGODB_PASSWORD: root
  #   # networks:
  #   #   - app_network
  #   network_mode: host



# networks:
#   app_network:
#     driver: bridge